spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb-prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    de.fhac.simpletodo: INFO