spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    de.fhac.simpletodo: DEBUG